name: terraform-apply

on:
  push:
    branches:
      - develop
      - master
      - main

jobs:

  accept_commit:
    runs-on: ubuntu-20.04
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo 'build is NOT skipped'

  terraform-apply:
    name: terraform-apply
    needs: accept_commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        run: |
          echo "##[set-output name=full_branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch_name

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.13.6

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-duration-seconds: 900

      - name: Terraform Apply
        run: |
          terraform init
          case ${{ steps.branch_name.outputs.full_branch }} in
            "develop" )
              echo 'terraform apply for dev environment.'
              terraform workspace select dev
              ;;
            "master" )
              echo 'terraform apply for production environment.'
              terraform workspace select production
              ;;
          esac
          terraform apply -auto-approve
        shell: bash
        working-directory: ./resources
